%YAML:1.0

# imgHandler
gaussian_size: 5
canny_threshold: 30
contours_threshold: 50

# pcHandler
depth_threshold: 0.1
scan_num: 64
diatance_threshold: 20
point_cloud_edge_threshold: 1.0
intensity_threshold: 0.15

# calibHandler
projection_parameters:
  fx: 7.215377e+02
  fy: 7.215377e+02
  cx: 6.095593e+02
  cy: 1.728540e+02
Tcl_real: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -7.1070899999999999e-03, -9.9976500000000001e-01,
       -2.0477200000000001e-02, -4.7463899999999998e-01,
       6.1682600000000001e-03, 2.0433500000000000e-02,
       -9.9977199999999999e-01, -7.2583900000000007e-02,
       9.9995599999999996e-01, -7.2317700000000002e-03,
       6.0215900000000003e-03, -2.6669399999999999e-01, 0., 0., 0., 1. ]
find_size: 3
search_radius: 5